title = "Love Addiction"

languages = [
    "ja",
    "ja-ko",
    "ko",
]

# titles translated
titles = { ja = "Love Addiction", ja-ko = "Love Addiction", ko = "Love Addiction" }

artist = "アルストロメリア"
album = "THE IDOLM@STER SHINY COLORS FR@GMENT WING 05"
composer = "Jam9,家原正樹"
genre = ""
year = "2019"
disk = 1
track = 2
duration = "03:55.00"

project = "THE iDOLM@STER SHINY COLORS"

[singers]
    [singers.all] # overrides default 'all' properties
    color = "#000000"
    ja = "みんな"
    ja-ko = "all"
    ko = "모두"

    [singers.amana]
    color = "#f53c71"
    ja = "大崎甘奈"
    ja-ko = "오사키 아마나"
    ko = "오사키 아마나"
    actor = "黒木ほの香"

    [singers.chiyuki]
    color = "#fbfbfb"
    ja = "桑山千雪"
    ja-ko = "쿠와야마 치유키"
    ko = "쿠와야마 치유키"
    actor = "芝崎典子"

    [singers.tenka]
    color = "#e75bec"
    ja = "大崎甜花"
    ja-ko = "오사키 텐카"
    ko = "오사키 텐카"
    actor = "前川涼子"
